---
- name: Configure gateway server
  hosts: gateway

  tasks:
    - name: Enable IP Forwarding on the Gateway
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        line: 'net.ipv4.ip_forward = 1'

    - name: Configure Internal Network Adapter
      community.general.nmcli:
        state: present
        conn_name: ens35
        ip4: 10.1.1.1/24
        type: ethernet

    - name: Configure gateway firewall
      ansible.posix.firewalld:
        zone: public
        permanent: true
        masquerade: true
        state: enabled

    - name: Reload Gateway firewall
      ansible.builtin.service:
        name: firewalld
        state: reloaded

- name: Gather remote host facts
  hosts:
    - dns
    - appa

- name: Configure DHCP server
  hosts: dhcp
  tasks:
    - name: Install dhcp-server
      ansible.builtin.package:
        name: dhcp-server
        state: present

    - name: Update dhcpd config
      ansible.builtin.blockinfile:
        path: /etc/dhcp/dhcpd.conf
        block: |
          authoritative;
          subnet 10.1.1.0 netmask 255.255.255.0 {
            range 10.1.1.50 10.1.1.254;
            option routers 10.1.1.1;
            option broadcast-address 10.1.1.255;
            option domain-name-servers 10.1.1.3, 172.16.0.1;
            default-lease-time 600;
            max-lease-time 7200;
          }
          host gateway {
            hardware ethernet {{ hostvars['gateway']['ansible_facts']['ens35']['macaddress'] }};
            fixed-address 10.1.1.1;
          }
          host dns {
            hardware ethernet {{ hostvars['dns']['ansible_facts']['ens33']['macaddress'] }};
            fixed-address 10.1.1.3;
          }
          host appa {
            hardware ethernet {{ hostvars['appa']['ansible_facts']['ens33']['macaddress'] }};
            fixed-address 10.1.1.4;
          }
        state: present

    - name: Configure dhcp firewall
      ansible.builtin.include_role:
        name: firewallservice
      vars: 
        firewall_reload_service: dhcp

    - name: Start and enable dhcpd
      ansible.builtin.service:
        name: dhcpd
        state: started
        enabled: true

- name: Configure DNS server
  hosts: dns
  gather_facts: false
  tasks:
    - name: Install BIND
      ansible.builtin.yum:
        name: bind
        state: present

    - name: Update dns config
      ansible.builtin.copy:
        src: ~/Documents/Training/Task5/named.conf
        dest: /etc/named.conf
        mode: "0777"

    - name: Create Zone Files
      ansible.builtin.copy:
        src: ~/Documents/Training/Task5/zones
        dest: /etc/named
        directory_mode: "0777"
        mode: "0777"

    - name: Allow dns traffic through firewall
      ansible.builtin.include_role:
        name: firewallservice
      vars:
        firewall_reload_service: dns

    - name: Start dns service
      ansible.builtin.service:
        name: named
        state: started
        enabled: true

- name: Reconfigure dns and app network adapters to use dhcp settings
  hosts:
    - dns
    - appa
  gather_facts: false

  tasks:
    - name: Set NICs to use dhcp
      community.general.nmcli:
        state: present
        conn_name: ens33
        method4: auto

    - name: Restart network managers
      ansible.builtin.service:
        name: NetworkManager
        state: restarted

- name: Reconfigure gateway to use hdcp settings
  hosts: gateway
  gather_facts: false

  tasks:
    - name: Set gateway to use dhcp
      community.general.nmcli:
        state: present
        conn_name: ens35
        method4: auto

- name: Restart all network cards to update with new dhcp settings
  hosts: all
  gather_facts: false
  tasks:
    - name: Restart Network Cards
      ansible.builtin.service:
        name: NetworkManager
        state: restarted

- name: Configure App server
  hosts: appa
  gather_facts: false

  vars_files:
    - vars/main.yml
    - vars/github_access_token.yml

  environment:
    PORT: "{{ app_port }}"
    TARGET_URL: "{{ url }}"

  tasks:

    - name: Change SELinux state to permissive
      ansible.posix.selinux:
        state: permissive
        policy: targeted

    - name: Install git package
      ansible.builtin.package:
        name: git
        state: present

    - name: Ensure App Data folder is empty
      ansible.builtin.file:
        path: /root/Data/
        state: absent

    - name: Download app files from github
      ansible.builtin.git:
        repo: "https://{{ TOKEN }}@github.com/Enterprise-Automation/trainee-challenge-node-app.git"
        dest: /root/Data

    - name: Install Node.js
      ansible.builtin.include_role:
        name: geerlingguy.nodejs

    - name: Enable traffic on app port
      ansible.posix.firewalld:
        zone: public
        port: "{{ app_port }}/tcp"
        permanent: true
        state: enabled

    - name: Reload firewall
      ansible.builtin.service:
        name: firewalld
        state: reloaded

    - name: Run Node App [Call app by running 'curl http://10.1.1.4:8000']
      ansible.builtin.command: node /root/Data/index.js
...
